Feedbacks
IF-093-Python/CultureAnalyzer pull request #20
Opened 2019-01-26 14:53 UTC by MrKreg

Created feedback app with CRUD. **Don't forget to install additional packages!**

2019-01-26 15:55 UTC, skhortiuk requested changes

2019-01-26 15:55 UTC, khortiuk commented on requirements.txt
> +pkg-resources==0.0.0
[FIX] Error while installing pkg
```
Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from versions: )
No matching distribution found for pkg-resources==0.0.0
```

2019-01-26 20:12 UTC, MrKreg commented on requirements.txt
> +pkg-resources==0.0.0
Done)

2019-01-27 20:41 UTC, skhortiuk approved these changes

2019-01-27 21:25 UTC, MarianMandziuk approved these changes

2019-01-27 21:31 UTC, kolinkovlad approved these changes

2019-01-27 21:38 UTC, merged