Feedbacks
IF-093-Python/CultureAnalyzer pull request #35
Opened 2019-02-05 10:41 UTC by MrKreg

Changes in this PR:
- changed Feedback model (added fields min_value,max_value and indicator)
- created Recommendation model
- moved const ITEMS_ON_PAGE to base_settings to follow DRY
- added SafePaginator class that extends django.core.Paginator and cathes common exceptions
- added SafePaginationListView that replaced Http404 response to first page when page parameter is string
- added validation for Feedback form to avoid min_value more than max_value

**You can use SafePaginationListView as parent class for your list view class to avoid pagination exceptions. And ITEMS_ON_PAGE from base_settings.**

2019-02-06 12:33 UTC, ygavenchuk requested changes

2019-02-06 12:33 UTC, ygavenchuk commented on feedbacks/forms.py
> +from .models import (
It would be better to write all imported classes in single line

2019-02-06 12:33 UTC, ygavenchuk commented on feedbacks/forms.py
> +__all__ = [
You don't need to enumerate each item in separate line.

2019-02-06 12:33 UTC, ygavenchuk commented on feedbacks/models.py
> +__all__ = [
You don't need to write each item in separate line

2019-02-06 12:33 UTC, ygavenchuk commented on feedbacks/templates/feedbacks/feedback_detail.html
> +{% endblock %}
Missed blank line at the end of file

2019-02-06 12:33 UTC, ygavenchuk commented on feedbacks/templates/feedbacks/recommendation_confirm_delete.html
> +{% endblock content %}
Missed blank line at the end of file

2019-02-06 12:33 UTC, ygavenchuk commented on feedbacks/templates/feedbacks/recommendation_form.html
> +{% endblock content %}
Missed blank line at the end of file

2019-02-06 12:33 UTC, ygavenchuk commented on feedbacks/templates/feedbacks/recommendation_list.html
> +{% endblock content %}
Missed blank line at the end of file

2019-02-06 12:33 UTC, ygavenchuk commented on feedbacks/views.py
> +        print(back)
Missed `print` statement.

2019-02-06 12:33 UTC, ygavenchuk commented on feedbacks/views.py
> +        return super().delete(self, request, *args, **kwargs)
You have 2 requests to DB: `get` & `delete`. Those requests should be run inside transaction only!

2019-02-06 12:33 UTC, ygavenchuk commented on feedbacks/views.py
> +        global feed
**WARNING**: "Code smells" detected!!! Global variable should be removed!

2019-02-06 12:33 UTC, ygavenchuk commented on feedbacks/views.py
> +        feed = Feedback.objects.get(pk=feedback)
Could you explain this statement? What's the reason for it?

2019-02-12 10:03 UTC, ygavenchuk requested changes
The PR looks a bit inaccurate. It would be nice to have it polished.

2019-02-12 10:03 UTC, ygavenchuk commented on feedbacks/validator.py
> +        min_value = rq_data.cleaned_data.get('min_value')
Please note, current implementation of `FeedbackValidator` is tuned exactly to `django.forms.ModelForm`. Therefore it isn't portable and can't be used anywhere else. Thus, there's no benefits to use separate validator's class. I'd propose a bit different implementation of it:
```python
# you may put exceptions bellow into separate file (python's module)
class CAError(Exception):
    pass

class FValidationError(CAError, ValueError):
    pass

class FeedbackValidator:
    @staticmethod
    def validate_min_value(rq_data):
        """
        @param dict rq_data:
        
        @raises FValidationError:
        """
        if rq_data.get('min_value') >= rq_data.get('max_value'):
            raise FValidationError('Min value must be less then max value')

# and usage:
#.... some code here
try:
    FeedbackValidator.validate(self.cleaned_data)
except FValidationError as err:
    self.cleaned_data.add_error('min_value', str(err))
# ... rest of your code here
```

2019-02-12 10:03 UTC, ygavenchuk commented on CultureAnalyzer/paginator.py
> +class SafePaginator(Paginator):
It might be worth to add all export stuff into `__all__` list

2019-02-12 10:03 UTC, ygavenchuk commented on CultureAnalyzer/view.py
> +class SafePaginationListView(ListView):
It might be worth to add all export stuff into `__all__` list

2019-02-12 10:03 UTC, ygavenchuk commented on feedbacks/tests.py
> +    def test_values(self):
Could you help me to understand the purpose of this test method? Do you try to ensure if django's models work correct?

2019-02-12 10:03 UTC, ygavenchuk commented on feedbacks/tests.py
> +class FeedbackTestCase(TestCase):
It might be worth to add all test cases into `__all__` list

2019-02-12 10:03 UTC, ygavenchuk commented on feedbacks/tests.py
> +class FeedbackFormTest(TestCase):
Let me draw you attention to the [ddt](https://ddt.readthedocs.io/en/latest/example.html) package. It might help you to reduce total amount of boilerplate code

2019-02-12 10:03 UTC, ygavenchuk commented on feedbacks/tests.py
> +    def test_values(self):
Could you help me to understand the purpose of this test method? Do you try to ensure if django's models work correct?

2019-02-14 11:51 UTC, ygavenchuk reviewed
Please, pay attention to `RecommendationCreateView`. It has a few suspicious statements. Could you double-checked them?

2019-02-14 11:51 UTC, ygavenchuk commented on feedbacks/exceptions.py
> +class CAError(Exception):
It might be worth to add all export stuff into `__all__` list

2019-02-14 11:51 UTC, ygavenchuk commented on feedbacks/tests.py
> +def form_data_generator(data):
Seems this function is redundant and might be removed

2019-02-14 11:51 UTC, ygavenchuk commented on feedbacks/tests.py
> +    @idata(form_data_generator(FEEDBACK_VALID_DATA))
You may avoid using any extra functions and/or wrappers by using trivial approach:
```python
@data(*FEEDBACK_VALID_DATA)
def test_valid_form(self, value)
```

2019-02-14 11:51 UTC, ygavenchuk commented on feedbacks/tests.py
> +    @idata(form_data_generator(FEEDBACK_INVALID_DATA))
You may avoid using any extra functions and/or wrappers by using trivial approach:
```python
@data(*FEEDBACK_INVALID_DATA)
def test_invalid_form(self, value)
```

2019-02-14 11:51 UTC, ygavenchuk commented on feedbacks/tests.py
> +    @idata(form_data_generator(list(range(-10, 10))))
Probably `list` is redundant here - `range` is Itereable.

2019-02-14 11:51 UTC, ygavenchuk commented on feedbacks/views.py
> +            Feedback.objects.get(pk=int(self.request.GET.get('feedback')))
Useless statement. Missed return value? If you like to check existence of record with given ID, it would be better to use the [.exists](https://docs.djangoproject.com/en/2.1/ref/models/querysets/#exists) method. 

Beside that, it seems like you want to get information from 2 models at the same time. If my suggestion is correct, probably you missed a transaction here.

2019-02-18 12:52 UTC, ygavenchuk approved these changes

2019-02-18 16:07 UTC, falled10 approved these changes

2019-02-19 09:16 UTC, merged