Сreating a user access system through a role group
IF-093-Python/CultureAnalyzer pull request #55
Opened 2019-03-18 09:46 UTC by IvanYukish

Creating an application permissions system. To add permissions to your directory, add PermissionPequiredMixin and select the appropriate permission.

2019-03-18 11:17 UTC, MrKreg requested changes

2019-03-18 11:17 UTC, MrKreg commented on feedbacks/tests.py
> +        self.assertEqual(response.status_code, 403)
Remove permissions from view instead of change tes

2019-03-18 12:48 UTC, falled10 requested changes

2019-03-18 12:48 UTC, falled10 commented on quiz/views.py
> +from django.contrib.auth.mixins import LoginRequiredMixin, \
You have unresolved import LoginRequiredMixin.

2019-03-18 12:48 UTC, falled10 commented on users/views.py
> +from .forms import UserRegisterForm, UserUpdateForm, GroupForm
You should have blank line before local imports see [pep8](https://www.python.org/dev/peps/pep-0008/#imports)

2019-03-18 12:48 UTC, falled10 commented on users/views.py
> +    queryset = Group.objects.all()
You use ```model = Group``` and ```queryset = Group.objects.all()``` can you use only one of them?

2019-03-18 12:48 UTC, falled10 commented on users/views.py
> +    success_message = 'Group: "%(name)s" was deleted successfully'
You have success_message here but have not SuccessMessageMixin, is it right?

2019-03-18 12:48 UTC, falled10 commented on users/views.py
> +    success_message = 'Country indicator: "%(name)s" was created successfully'
You have success_message here but have not SuccessMessageMixin, is it right?

2019-03-18 13:02 UTC, MrKreg requested changes

2019-03-18 13:02 UTC, MrKreg commented on feedbacks/tests.py
> +        self.assertTemplateUsed(response, "feedbacks/feedback_list.html")
Can you explain why did you change this row?

2019-03-18 13:02 UTC, MrKreg commented on indicators/views.py
> +from django.contrib.auth.mixins import LoginRequiredMixin, \
Can you follow team agreements about multiple import with scopes?

2019-03-19 12:40 UTC, MrKreg submitted a review, later dismissed

2019-03-21 09:41 UTC, falled10 approved these changes

2019-03-21 09:51 UTC, kolinkovlad approved these changes

2019-03-21 10:17 UTC, rostIvan approved these changes

2019-03-21 10:17 UTC, merged