Custom middlewares
IF-093-Python/CultureAnalyzer pull request #75
Opened 2019-03-22 13:43 UTC by kolinkovlad

Added custom middlewares: AuthRequiredMiddleware, which realize redirect according to permissions and SwitchSessionDataMiddleware, which realize switching session data between stored and current sessions.

2019-03-22 14:21 UTC, rostIvan commented on CultureAnalyzer/middleware.py
> +        return response
You can to extract some of these lines in __call__ and divide it on methods

2019-03-22 14:36 UTC, MrKreg requested changes

2019-03-22 14:36 UTC, MrKreg commented on CultureAnalyzer/middleware.py
> +
Reformat your code with IDE!

2019-03-22 14:36 UTC, MrKreg commented on CultureAnalyzer/middleware.py
> +                    session_data=encoded_data, expire_date=expire_date)
It would be better to wrap this piece of code into transaction.

2019-03-23 20:55 UTC, rostIvan commented on CultureAnalyzer/middleware.py
> +        return response
simply 
``` python 
return self.get_response(request) 
```

2019-03-23 22:49 UTC, rostIvan commented on CultureAnalyzer/middleware.py
> +
I'm not sure, but maybe the next lines should be also inside `transaction`
https://github.com/IF-093-Python/CultureAnalyzer/blob/df68f76ca428c68e7e6e28f0648aaf939786920e/CultureAnalyzer/middleware.py#L46-L47

You can to append this part of code to `_switch_session_data` method

2019-03-23 22:51 UTC, kolinkovlad commented on CultureAnalyzer/middleware.py
> +        return response
something like: return = self.get_response(request) ?

2019-03-24 15:17 UTC, MrKreg approved these changes

2019-03-24 16:04 UTC, falled10 approved these changes

2019-03-25 09:51 UTC, merged