Indicator new tests
IF-093-Python/CultureAnalyzer pull request #77
Opened 2019-03-23 16:18 UTC by MarianMandziuk

Provide new tests for indicators model and views

2019-03-23 16:37 UTC, falled10 requested changes

2019-03-23 16:37 UTC, falled10 commented on indicators/tests/test_models.py
> +)
Can you move this code into test_models_data.py for example?

2019-03-23 16:37 UTC, falled10 commented on indicators/tests/test_views.py
> +    )
Can you move this code into test_views_data.py for example?

2019-03-23 16:37 UTC, falled10 commented on indicators/tests/test_views.py
> +        role_name = 'Admin'
Can you remove this magic string or replace it with ADMIN_ID from CultureAnalyzer.py?

2019-03-23 16:37 UTC, falled10 commented on indicators/tests/test_views.py
> +        role_name = 'Admin'
Can you remove this magic string or replace it with ADMIN_ID from CultureAnalyzer.py?

2019-03-23 19:03 UTC, MrKreg requested changes

2019-03-23 19:03 UTC, MrKreg commented on indicators/tests/test_views.py
> +        response = self.client.get("/indicators/")
On my opinion it would be better to use reverse method here.

2019-03-23 19:03 UTC, MrKreg commented on indicators/tests/test_views.py
> +        response = self.client.get("/indicators/?page=2")
On my opinion it would be better to use reverse method here.

2019-03-23 19:03 UTC, MrKreg commented on indicators/tests/test_views.py
> +        response = self.client.get(f"/indicators/?indicator_search"
On my opinion it would be better to use reverse method here.

2019-03-23 19:03 UTC, MrKreg commented on indicators/tests/test_views.py
> +        response = self.client.get("/indicators/9/update/")
On my opinion it would be better to use reverse method here.

2019-03-23 19:03 UTC, MrKreg commented on indicators/tests/test_views.py
> +        response = self.client.get("/indicators/create/")
On my opinion it would be better to use reverse method here.

2019-03-24 11:49 UTC, falled10 approved these changes

2019-03-24 12:12 UTC, kolinkovlad approved these changes

2019-03-24 15:17 UTC, MrKreg approved these changes

2019-03-24 15:47 UTC, merged