Groups
IF-093-Python/CultureAnalyzer pull request #79
Opened 2019-03-24 16:08 UTC by Yarema-Kryven

Added views, urls and templates for Mentor_Groups, Shedule and Invitation

2019-03-24 18:27 UTC, falled10 requested changes

2019-03-24 18:27 UTC, falled10 commented on groups/views.py
> +from django.shortcuts import redirect
Can you connect this 2 import? Something like this ``` from django.shortcuts import get_object_or_404, redirect

2019-03-25 13:40 UTC, MrKreg approved these changes

2019-03-25 13:40 UTC, falled10 approved these changes

2019-03-25 13:41 UTC, merged