Api permissions
IF-093-Python/CultureAnalyzer pull request #82
Opened 2019-03-24 18:47 UTC by IvanYukish

Provision of access control roles for rest framework

2019-03-24 22:32 UTC, MrKreg requested changes

2019-03-24 22:32 UTC, MrKreg commented on api/views.py
> +        'destroy': [ADMIN_ID],
Destroy is mentor scope too.

2019-03-25 13:54 UTC, MrKreg requested changes

2019-03-25 13:54 UTC, MrKreg commented on api/permissions.py
> +                [self.is_in_group(request.user, group_id) for group_id in
In my opinion this else statement is useless

2019-03-25 13:54 UTC, MrKreg commented on api/permissions.py
> +        Сhecking which group is the user
What are you meaning in that docstring?

2019-03-25 14:13 UTC, MrKreg submitted a review, later dismissed

2019-03-25 21:10 UTC, falled10 approved these changes

2019-03-25 21:56 UTC, MrKreg approved these changes

2019-03-25 22:00 UTC, merged